import React, { Component } from 'react';
 
import AdItem from './AdItem.js';
import { Typography } from 'rmwc/Typography';
import { Modal, ModalHeader, ModalBody, ModalFooter } from 'reactstrap';
import { CardMedia } from 'rmwc/Card';


export default class Grid extends Component {

	constructor(props) {
		super(props); 
		this.state = {
			modal: false, 
			item: {}
		}; 

		this.toggle = this.toggle.bind(this); 
	}

	toggle(item) {
  		this.setState({
  			modal: !this.state.modal, 
  			item: item
  		});  	}

	getAdItem() {
	    return [
			{ _id: 1, headline: 'VW Cheats the Test', year: 2015, industry: 'Automotive', description: 'The International Council on Clean Transportation found in 2015 that Volkswagon had been cheating the United States disesel emissions test. It was determined that VW had developed a software would enable the "full emission-control systems" when the car was being tested, thus appearing to be "clean". Without the emission control on, the car was said to produce 40 times the standard nitrogen oxide emission. The Federal Trade Commission sued Volkswagon for misleading advertising of "Clean Diesel" vehicles. According to the FTC, Volkswagon decieved their customers for 7 years, claiming over 5 million desiel vehicles worldwide under the guise of "low-emission, environmentally friendly". As a result of the suit, CEO Martin Winkerton stepped down from his position.', img: ["https://amp.businessinsider.com/images/5615493cbd86ef18008c00c4-1920-1440.jpg"], relLinks: ["http://www.businessinsider.com/heres-what-volkswagen-did-and-how-they-got-caught-2015-9?r=UK&IR=T"]},
			{ _id: 2, headline: 'Activa\'s "Clinical" Lie', year: 2010, industry: 'Food', description: 'In 2010 the Federal Trade Commission sued The Dannon Company for deceptive advertising of their DanActive dairy drink. According to advertising on the label as well as in print, TV and radio, Dannon claimed the drink was scientifically proven to help prevent colds and the flu as well as relieve intestinal irregularity. In a television ad featuring a famous celebrity, Dannon claimed that the drink was “clinically proven to help regulate your digestive system in two weeks”. The FTC successfully proved that Dannon had no scientific evidence that their dairy drink helped “regulate your digestive system”, or that it prevented the flu or cold symptoms.', img: ["https://foodtruthfreedom.files.wordpress.com/2015/12/activia.jpg?w=820"], relLinks: ["https://www.ftc.gov/news-events/press-releases/2010/12/dannon-agrees-drop-exaggerated-health-claims-activia-yogurt"]},
			{ _id: 3, headline: 'Sears', year: 2013, industry: 'Textiles', description: 'Sears, Roebuck and Company, the department store chain colloquially known as Sears, agreed to pay $475,000 for violating the Textile Products Identification Act in 2013. Sears had received warnings from the FTC in 2010 for labelling its “100% Pure Bamboo” line of products. Instead of bamboo, these products were made using rayon- a synthetic cellulose fiber. Advertising the products as made out of bamboo suggested that they were “green” and environment friendly.  In reality, rayon is manufactured using toxic chemicals in a process known for its hazardous byproducts. The implication that such products were environment friendly with underlying damaging processes clearly misleads consumers and violates their right to knowledge of the products they are purchasing. Despite the warning in 2010, Sears did not alter its marketing strategy until the company reached a settlement with the FTC in 2013. Macy’s and Amazon were also fined, though lesser sums, for the same violation, totaling $1.3 million in fines.', img: ["http://i.dailymail.co.uk/i/pix/2013/01/08/article-2259017-16CF8274000005DC-799_306x269.jpg"], relLinks: ["http://time.com/107224/misleading-products/"]},
			{ _id: 4, headline:'Kellogg', year:2011, industry: 'Food', year: 2011, description: 'Kellogg agreed to a $4 million settlement with the FTC in 2011 surrounding the false advertising of their Frosted Mini Wheats cereal. Kellogg, the world\'s largest cereal producer, claimed the breakfast food was "clinically shown to improve kids\' attentiveness by nearly 20%". According to the complaint by the FTC, the study on child "attentiveness" only yielded a 20% increase in attentiveness in 1 out of every 9 children tested, and only 50% of the children participating in the study showed any changes in attentiveness. Following the settlement, Kellogg has dropped the advertising campaign and since adjusted the claims made about health and focus.', img: ["http://media.cleveland.com/taste_impact/photo/frostedjpg-94cc5b1de550cf7b_medium.jpg"], relLinks: ["https://www.ftc.gov/news-events/press-releases/2009/04/kellogg-settles-ftc-charges-ads-frosted-mini-wheats-were-false"]},
			{_id: 5, headline:'Lumos Lab', year: 2016, industry: 'Technology', description: 'Luminosity, the popular gaming application designed and marketed as "brain training", has agreed to a $2 million settlement with the FTC. According Luminosity, by playing mobile app game for 10 to 15 minutes up to four times a week, consumers could expect an improvement in everyday tasks in school, work life as well as athletics. The company also claimed that the games reduced "age-related cognitive decline" and protect against dementia and Alzheimer\'s disease. The company not only advertised in traditional manners such as television, radio, and print, but also increased traffic to their website by purchasing keywords such as memory, cognition, dementia and Alzheimer\'s through Google\'s AdWords. It was found that Lumos Lab had failed to gather sufficient scientific evidence surrounding their claims of improved mental health benefits. Following the settlement, Lumos Lab has agreed to publicly display their scientific finding as they relate to their popular mobile applications.', img: ["https://2.bp.blogspot.com/-9m2JCqjWdd0/WgYAjAQHyYI/AAAAAAAAJ_o/v6t-PXSihBYxs5kfxj1Kfn86VCRYjQNwQCLcBGAs/s1600/lumosity_9y3c.1280.jpg"], relLinks: ["https://www.ftc.gov/news-events/press-releases/2016/01/lumosity-pay-2-million-settle-ftc-deceptive-advertising-charges"]},
			{_id: 6, headline:'Costa Del Mar', year: 2018, industry: 'Apparel', description: 'Costa Del Mar is being sued for the misleading advertising of the warranty on their popular fishing sunglasses. The warranty boasts a "backed for life" label and additionally claims "no gimmick" and "no disclaimers". The warranty is labeled on every box of sunglasses sold as well as on their website. Written into the "backed for life" warranty, Costa includes the right of a "nominal fee". It was determined, however, that "nominal fee" for repairs totaled more than $200 for consumers, depending on the damage the glasses sustained. The inclusion of "nomical fees" allows for the popular manufacturer the ability to include repair and replacement fees, however, the "backed for life" warranty leads the consumer to believe the sunglasses maintain a true warranty without excess fees included. Ironically, the "no gimmick" claim of the popular sunglasses company is, in fact, a gimmick, designed to deceive consumers. Costa Del Mar is currently in a class-action lawsuit in the state of Texas surrounding the deceptive advertising of their "backed for life" warranty.', img: ["https://ssli.ebayimg.com/images/g/4K0AAOSw~o5aV8c1/s-l1600.jpg"], relLinks: ["https://www.truthinadvertising.org/wp-content/uploads/2018/04/Burden-v-Costa-Del-Mar-complaint.pdf"]}, 
			{_id: 7, headline:'L\'Oreal', year: 2014, industry: 'Cosmetics', description: 'In 2014, the popular cosmetic company, L\'Oreal settled a lawsuit with the FTC surrounding false advertising of an anti-aging skin care product: L\'Oreal Paris You Code skincare. According to the cosmetic brand whose advertisements were aired in print, on radio, television as well as through the internet and various social media outlets, the lotion had the ability to "boost genes\' activity and stimulate the production of youth proteins". The FTC would that these claims were not only false and unsubstantiated by any clinical research, despite the "clinically proven" tag line used in the advertising. The cosmetic brand aired the advertisements in both English and Spanish.', img: ["https://www.ftc.gov/system/files/attachments/press-releases/loreal-settles-ftc-charges-alleging-deceptive-advertising-anti-aging-cosmetics/loreal-ad-full.jpg"], relLinks: ["https://www.ftc.gov/news-events/press-releases/2014/06/loreal-settles-ftc-charges-alleging-deceptive-advertising-anti"]},
			{_id: 8, headline:'Vibram', year:2014, industry: 'Apparel', description: 'Vibram USA, the company that makes the Vibram FiveFinger, a close-fitting shoe attempting to mimic a bare foot, agreed to settle a class action lawsuit in 2014 that accused the company of making unsubstantiated claims on the health benefits of its footwear. The company gained market share with a spike in the popularity of minimalist running gear and experienced soaring sales with the pictured advertisement campaign “5 reasons to wear or train in Vibram FiveFingers”. In this campaign, the company listed various health benefits, including strengthened muscles and injury prevention for consumers. These claims were, however, unsubstantiated and discontinued after the court settlement, under which Vibram agreed to refund customers who bought its shoes. The total settlement amounted to $3.75 million. Despite reaching the settlement, Vibram issued a statement denying any malpractice: “Vibram expressly denied and continues to deny any wrongdoing alleged in the Actions, and neither admits nor concedes any actual or potential fault”.', img: ["https://i.pinimg.com/236x/b2/a3/85/b2a3859a9791e317cc4f08db6335382a--vibram-shoes-toe-socks.jpg"], relLinks: ["https://www.nbcnews.com/business/consumer/vibram-fivefinger-shoes-give-refunds-over-allegedly-bare-health-claims-n101301"]}, 
			{_id: 9, headline:'Emergen-C', year:2013, industry: 'Food', description: 'Alacer corporation, the parent company which owns the dietary supplement Emergen-C, reached a $6.5 million settlement in late 2013 over its misleading claims that the supplement boosts energy, the immune system, and metabolism. These claims, imaged on the side of the product box, were indeed unsubstantiated and had no scientific evidence supporting them. This settlement provided reimbursement to individuals who had consumed Emergen-C from June of 2006 to February of 2012, while these claims were included on the box. The complaint filed against Alacer alleges that the company misleadingly represents that the supplement will reduce the risk of colds and flu without scientific evidence. This deceptive marketing occurred for 6 years before being addressed.', img: ["https://i1.wp.com/images-na.ssl-images-amazon.com/images/I/51Qp%2BZRRxCL.jpg?w=696&ssl=1"], relLinks: ["https://topclassactions.com/lawsuit-settlements/closed-settlements/13271-emergen-c-class-action-lawsuit-settlement/"]}, 
			{_id: 10, headline:'Coles SuperMarket', year: 2015, industry: 'Food', description: 'Coles, one of the largest supermarket chains in Australia, was recently fined $2.5 million for misleading advertising of their baked goods. The slogan "Baked Today, Sold Today" and "Freshly Baked in Store" were branded in stores and labeled on all baked goods sold. It was determined by the Australian Federal Court, however, that the baked goods had been partially baked and frozen off-site before being shipped to stores to finish the baking process. In a statement following the accusation, Coles claimed they did not "deliberately set out to mislead anybody", yet the campaign demonstrates an attempt to attract consumers under the assumption of in-store, freshly baked goods. The claim "freshly baked in stores" misleads customers to believe goods are freshly baked from scratch in stores on a daily basis, despite being partially baked and frozen off-site. The deceptive slogan gives Coles an unfair competitive advantage over competitors, specifically small, independently owned bakeries that specialize in freshly baked goods daily. The Australian Competition and Consumer Commission reported the supermarket chain had been using the "Baked Today, Sold Today" slogan as well as other for three years in over 600 different stores across the country. In addition to the fine of $2.5m, Coles since removed the slogans from all stores and packaging.', img: ["https://www.productsafety.gov.au/system/files/coles%20cookie.jpg"], relLinks: ["https://mumbrella.com.au/coles-fined-2-5m-for-misleading-advertising-on-claims-bread-products-were-baked-today-286555"]}, 
			{_id: 11, headline:'Nissan, TBWA Settle with FTC', year: 2014, industry: 'Automotive', description: 'In 2014, Nissan North American and its advertising company, TBWA Worldwide reach a settlement with the FTC over a 30 second commercial, “Hill Climb”, which had misleading implications of the Nissan Frontier\’s capabilities. In the commercial, a Frontier pushes a stranded dune buggy up a steep sand dune. In reality, the truck and dune buggy were towed up the incline using cables. The video was filmed in a style that made it appear homemade, contributing to the realistic nature of the commercial. Despite a small disclaimer in print, saying “Fictionalization. Do not attempt.”, the FTC maintained that the company cannot use misleading demonstrations to misrepresent what its product can do. Neither Nissan North American nor TBWA Worldwide were forced to pay fines in this settlement, but the advertisement campaign was altered to reflect the car’s actual capabilities.', img: ["https://i.ytimg.com/vi/qlB--MKzlgM/maxresdefault.jpg"], relLinks: ["https://www.youtube.com/watch?v=qlB--MKzlgM", "http://adage.com/article/news/nissan-tbwa-settle-ftc-faked-commercial/291269/"]},
			{_id: 12, headline:'iFocus', year: 2015, industry: 'Technology', description: 'Texas company Focus Education marketed a software called the ifocus System, which includes the computer game Jungle Rangers which is advertised to permanently improve children’s focus, memory, attention, behavior, and school performance. This software sold for $214.75 and generated $4.5 million in sales between 2012 and 2013. Infomercials and the company website claim that Jungle Rangers had scientifically proven memory and attention brain training exercises which were designed to improve focus, concentration and memory. The company claimed that these benefits were scientifically proven, which the FTC found to be a fabricated statement. The FTC’s settlement prohibits Focus Education from making such claims unless the claims are non-misleading and are supported by competent and reliable scientific evidence.', img: ["http://www.mommylivingthelifeofriley.com/wp-content/uploads/2012/12/ifocus-Goals.jpg"], relLinks: ["https://www.ftc.gov/news-events/press-releases/2015/01/makers-jungle-rangers-computer-game-kids-settle-ftc-charges-they"]},
			{_id: 13, headline:'Tesco “What Burgers Have Taught Us”', year: 2013, industry: 'Food', description: 'In 2013, UK supermarket chain Tesco, along with some other companies in the food industry, faced PR difficulties of preserving their image after the fraudulent Horsemeat Scandal plagued the British and Irish food chain. After its meat products tested positive for having horse DNA, Tesco ran a two-page advertisement in national newspapers with the headline “What burgers have taught us.” This spread implied that issues with meat standards extended across the entire food industry. Tesco\’s advertisement alleged that all retailers and suppliers had products contaminated with horsemeat despite a failure to actually identify this claim as true. This allegation was made with no evidence and was banned by the Advertising Standards Authority for being misleading.', img: ["http://payload161.cargocollective.com/1/7/251742/5533978/burgers_1200.jpg"], relLinks: ["https://uk.reuters.com/article/uk-britain-retail-tesco/uk-ad-watchdog-raps-tesco-on-horsemeat-campaign-idUKBRE9830F220130904"]},
			{_id: 14, headline:'Hyundai Offers $85 Million to Settle Horsepower Suit', year: 2004, industry: 'Automotive', description: 'In 2001, the Korean Ministry of Construction and Transportation uncovered a misrepresentation in which the automaker overstated the horsepower of certain Hyundai and Kia car models exported to the United States. About 460,000 consumers bought 1996-2002 model vehicles with miscalculated horsepower. Miscalculations overstated engine power by as much as 10%, and the average misstatement among the 1.3 misrepresented vehicles was 4.6 horsepower. In 2004, the class action settlement was reached and Hyundai reimbursed consumers up to $225, bringing the settlement sum to $85 million.', img: ["https://s3.us-east-2.amazonaws.com/irwin-hyundai/elantra/2018-Hyundai-Elantra-Performance.jpg"], relLinks: ["https://www.nytimes.com/2004/06/22/business/hyundai-settles-horsepower-suit.html"]},
			{_id: 15, headline:'Olay Photoshopping', year: 2009, industry: 'Cosmetics', description: 'In 2009 the British Advertising Authority banned an Olay Definity eye illuminator advertisement featuring popular British personality Twiggy. The skin care product is marketed to "reduce the look of wrinkles and dark circles for brighter, younger-looking eyes". The banned advertisement features the 60 year old Twiggy with clear, wrinkle-free skin. After being publicly criticized for the obvious doctored photo, Olay released a statement claiming that "consumers were likely to expect a degree of glamour" and that it was "routine practice to use post-production techniques to correct for lighting and other minor photographic deficiencies". The Proctor and Gamble owned cosmetics company did not receive any formal fines, however they agreed to remove the advertisement from circulation. By admitting to "post production techniques", Olay reveals the obvious intention to deceive consumers of the actual effects of the product. The ability to retouch and edit pictures post-production leaves the door wide open for a variety of industries to mislead the consumer and should be policed.', img: ["https://i.pinimg.com/originals/df/a4/55/dfa455888b4b108cca170f6dbc4ddff5.jpg"], relLinks: ["https://www.theguardian.com/media/2009/dec/16/twiggys-olay-ad-banned-airbrushing"]},
			{_id: 16, headline:'Peabody Energy\'s "Clean Coal"', year: 2014, industry: 'Energy', description: 'In February of 2014, Peabody Energy published an advertisement in the European edition of the Financial Times that came under heavy criticism for claiming "clean coal". Peabody, the world\'s largest private sector coal company, boasted their effort to "end energy poverty, increase access to low-cost electricity and improve emissions using today\'s advanced clean coal techniques". Unfortunately for Peabody Energy, "clean coal" does not really exist. Science has proven that coal is one of the dirtiest fossil fuels being used today and is the largest source of man-made CO2 emissions on the planet. The competitive advantage for coal powered energy is that it is, in fact, one of the cheapest ways to create electricity, however, it has been clearly demonstrated to have harmful effects for not only the environment as a whole, but also on the individual level. According to The Guardian, nearly 7 million people died in 2012 as a result of air pollution systems. By claiming "low-cost electricity", Peabody inherently targets more impoverished communities. Combining the target audience with the deception of "clean coal", Peabody\'s deceptive advertising came under much scrutiny and was removed from circulation.', img: ["http://members.greenpeace.org/gpblog/media/1417012/cleancoalcool.jpg"], relLinks: ["https://www.theguardian.com/sustainable-business/2014/aug/26/advertising-standards-authority-rules-peabodys-clean-coal-ad-misleading"]},
			{_id: 17, headline:'Origin Companies Ordered to pay Penalties of $325,000 for Misleading Consumers About Discounts Under Energy Plans', year: 2015, industry: 'Energy', description: 'The Australian Competition and Consumer Commission ordered that Origin Energy Limited pay fines summing $325,000 for violating Australian Consumer Law by making misleading claims to consumers regarding their potential eligibility for a discount on energy usage charges for electricity and natural gas. In early 2013, Origin published on its website and in confirmation packs sent to consumers that under a DailySaver energy plan, consumers would receive a discount of up to 16% off of electricity charges and 12% off of natural gas charges. However, consumers received a reduced discount because the rates used to calculate usage charges under the DailySaver energy plan were higher than the rates under the subsidiaries standard retail contracts. The Federal Court of Australia found that these representations were misleading and brought these proceedings against Origin as a step in its work in a priority area for 2014; consumer protection in the energy sector.', img: ["https://files.ozbargain.com.au/n/37/204637x.jpg?h=ebc6e97e"], relLinks: ["https://www.smartcompany.com.au/business-advice/legal/origin-energy-in-hot-water-over-alleged-false-conduct/"]},
			{_id: 18, headline:'Apple\'s Memory Problem', year: 2015, industry: 'Technology', description: 'In September of 2014, Apple CEO Tim Cook announced the release of the iPhone 6 series. In his keynote speech, Cook claimed the new iPhone 6 and 6s to be "the biggest advancement in the history of the iPhone". The major part of the advancement described by Cook was the introduction of Apple\'s new iOS 8 software. The new processing software reportedly takes up a total of 3.3 GB of storage, which represents nearly 21% of the 16 GB phone. In January of 2015, two Apple customers from Miami sued the tech giant for misleading consumers. The iPhone 6 and 6s were both advertised as boasting 16GB of internal storage available on the phone. In reality, the required iOS 8 processing software took up over a fifth of the available storage on the device. In a statement following the filing of the suit, the plaintiffs stated "Apple\'s misrepresentation and omissions are deceptive and misleading because they omit material facts that an average consumer would consider in deciding whether to purchase its product". Alongside the internal storage offered on the device, Apple also offers iCloud, a cloud based service that provides customers with additional memory storage. Because Apple\'s iCloud feature is not free, the plaintiffs claim that the failure to include the 3.3GB of storage necessary for iOS is intentional and leads to consumers to purchase the cloud service. By selling an iPhone with nearly 21% less internal storage than advertised coupled with Apple\'s pay-to-use iCloud service, the deceptive advertising appears to be intentional.', img: ["https://m1.awokcdn.com//upload/resize_cache/iblock/678/325_280_1/6784c3fc44f7a408dc4dc096ef215a81.png", "http://i.dailymail.co.uk/i/pix/2015/01/02/2460240A00000578-2894228-The_lawsuit_was_filed_by_Paul_Orshan_and_Christopher_Endara_from-a-12_1420193777360.jpg"], relLinks: ["http://kdvr.com/2015/01/03/apple-sued-because-iphone-isnt-really-16-gb/"]},
			{_id: 19, headline:'Gillette\'s Not So Home Made', year: 2018, industry: 'Consumer Products', description: 'The popular razor company Gillette aired an ad campaign centered on the theme of patriotism. The advertisements, which included a 30-second television ad as well as advertisements in print and on various social media outlets highlighted the Boston based headquarters and factory. The slogan "Made in Boston" was stamped on the printed advertisements and the television ad showed clips of Gillette factory workings appearing to be creating razors and other products in the Boston factory. An investigation headed by TruthInAdvertising.org (TINA.org) found that of the 17 products examined, only two packages were labeled "Made in the USA" with the rest being labeled as made in Brazil, Poland or China. Despite the "Made in Boston" campaign and the television advertisement suggesting manufacturing in Boston, Gillette does the majority of their product manufacturing overseas. The FTC has established specific guidelines for products to be labeled "Made in USA", primarily requiring "all or virtually all" of the product to be made in the United States. Because Gillette\'s products do not include the "Made in USA" label on the package, they are not in violation of the FTC guidelines. The ad campaign, however, misleads consumers to believe that the product they are purchasing has been manufactured in the United States, and more specifically in Boston. Gillette, like many other companies, understands that patriotism sells, and therefore leverages their Boston heritige through misleading advertising to gain a competitive advantage over competing companies.', img: ["https://www.truthinadvertising.org/wp-content/uploads/2017/12/Gillette-tweet-built-in-Boston-since-1901.png"], relLinks: ["https://globenewswire.com/news-release/2018/01/23/1299266/0/en/Gillette-Engaged-in-Deceptive-Made-in-USA-Marketing-According-to-Ad-Watchdog-TINA-org.html"]},
			{_id: 20, headline:'Wrigley Settles False-Ad Class Action for $6M', year: 2010, industry: 'Food', description: 'Gum company Wrigley was forced to create a fund containing up to $6 million to reimburse consumers who bought Eclipse gum under deception by the corporation between 2008 and 2010. Starting in 2008, Eclipse began advertising that its sugar free gum had natural germ-killing capabilities. This claim was based on the fact that Eclipse gum and mints contain magnolia plant extract, which Wrigley claims to have studied and proven kill 20 times more dental bacteria in half an hour than a placebo mint. However, the court ruled that this study is not sufficient for Wrigley to advertise that Eclipse gum was “scientifically proven to help kill the germs that cause bad breath”. As a result, Wrigley was forced to discontinue such labelling and advertising claims and distribute $6 million to consumers.', img: ["http://image.minyanville.com/assets/FCK_Jan2011/images/freddy/2012/03/02/img_04.jpg"], relLinks: ["https://www.forbes.com/sites/docket/2010/06/01/wrigley-settles-false-ad-class-action-for-6m/#d75f97e4f08b"]},
			{_id: 21, headline:'Sensa\'s Diet Deceit', year: 2014, industry: 'Food', description: 'In 2014, Sensa Products was ordered a heavy fine of $46.5 million by the FTC due to their diet product. The dietary product is a powder that consumers are instructed to sprinkle over their typical meal. According to Sensa, the powered is designed to make the food smell and taste better as well as make the user feel more full with less food. The advertisement campaign which was broadcasted through multiple different outlets including television, radio, print and online informed customers that scientific trials had been conducted that proved the success of the seemingly magical powder. The scientific evidence was supported by Sensa part-owner Dr. Alan Hirsch. It was determined by the FTC Dr. Hirsch scientific evidence was unsubstantiated and failed to demonstrate sufficient evidence of the success of the powder additive. Sensa marketed Dr. Hirsch\'s weight loss claims from 2008 to 2012, totaling more than $350 million in sales. Following the FTC investigation and ensuing fine, Sensa is required to provide "two adequate and well-controlled human clinical studies" supporting any dietary claims made about their products. Additionally, Dr. Hirsch is no longer allowed to include endorsement of weight loss products unless he has disclosed evidence of proper scientific studies substantiating any claims.', img: ["http://static.adweek.com/adweek.com-prod/wp-content/uploads/files/news_article/sensa-hed-2013.jpg"], relLinks: ["https://www.ftc.gov/news-events/press-releases/2014/01/sensa-three-other-marketers-fad-weight-loss-products-settle-ftc"]},
			{_id: 22, headline:'Sketchers Will Pay $40 Million to Settle FTC Charges That It Deceived Consumers with Ads for "Toning Shoes"', year: 2012, industry: 'Apparel', description: 'The Federal Trade Commission reached a settlement with Sketchers USA, Inc. over a deceptive advertising campaign in which the shoe company made unfounded claims about the effect of using its products. Shape-ups and other “toning” shoes promise to help people lose weight, tone muscles, and improve cardiovascular health. These advertising claims were not supported by scientific findings and resulted in the FTC settlement in 2012. Sketchers advertisements included these promises and even endorsements from a chiropractor who recommended the product based on results of an “independent” study, which the FTC found did not produce the results claimed in the advertisement. The FTC complaint charged that Sketchers violated federal law by making deceptive advertising claims, including falsely representing that clinical studies backed up the claims. As a result, Sketchers was prohibited from including claims about strengthening, weight loss, and any other health or fitness-related benefits unless they are true and backed by scientific evidence.', img: ["http://1.bp.blogspot.com/-NMlhsWCQGHo/T_2WcwNNg7I/AAAAAAAABqM/Tm4iG50DSto/s640/skechers_shape-ups.png"], relLinks: ["https://www.ftc.gov/news-events/press-releases/2012/05/skechers-will-pay-40-million-settle-ftc-charges-it-deceived"]},
			{_id: 23, headline:'No So Fruit Snacks', year: 2015,industry: 'Food', description: 'Promotion in Motion, the company responsible for the manufacturing and marketing of the popular Welch\'s Fruit Snacks is in a class action lawsuit for their deceptive marketing of the popular snack. Along with the actual name of the product, Fruit Snacks, the packaging includes images of real pieces of fruit as well as the claim "Made with Real Fruit". A closer look at the back of the packaging reveals that the vending machine staple is made of primarily manufactured sugars, nearly 40% of the ingredients, and lacks almost all of the nutritional value included in fruit. The marketing strategy employed by Promotion in Motion demonstrates obvious attempt to deceive the consumer of the actual health benefits of the snack. The popular gummy is not a replacement for a piece of fruit, as the label may suggest, but instead is more on par with a candy such as gummy bears or Sour Patch Kids. The misleading packaging intentionally deceives consumers to expect actual nutritional value in Welch\'s Fruit Snacks.', img: ["https://imagesvc.timeincapp.com/v3/mm/image?url=https%3A%2F%2Ffortunedotcom.files.wordpress.com%2F2015%2F09%2Fimg_1634.jpg&w=800&q=85"], relLinks: ["http://fortune.com/2015/09/25/welchs-fruit-snacks-class-action/"]},
			{_id: 24, headline:'Classmates.com Settles False Advertising Suit', year: 2015,industry: 'Technology', description: 'In 2010, High School reunion website Classmates.com reached a settlement in a Class Action lawsuit claiming that the website had deceived users into purchasing a membership. The complaint held that users would receive a message from Classmates.com stating that an old classmate of theirs intended to get in touch. In order to see the alleged message, a user needed to upgrade their membership status. After paying for an elevated membership status, users would find that nobody had sent them a message, and the original email leading them to pay for a membership upgrade was fabricated. The settlement reached requires that Classmates.com have an updated privacy policy with a more transparent explanation of the messaging feature.', img: ["http://monicagallagher.com/wp-content/uploads/2014/10/cc_Welcome_day0_academic.png"], relLinks: ["https://www.lexology.com/library/detail.aspx?g=3e9d1127-46d6-4b7d-ae42-bebd9306128a"]}
		];
  	}

  	renderItems() {
	    return this.getAdItem().map((item) => (
	      <AdItem key={String(item._id)} item={item} onClick={this.toggle.bind(this, item)} />
	    ));
	}

	render () {
		return (
			<div>
				{this.renderItems()}
				<Modal isOpen={this.state.modal} toggle={this.toggle} size='lg'>
		          <ModalHeader toggle={this.toggle}>
		          	<div className='expanded-main-img-container'>
		          		<img src={this.state.item.img} className='expanded-main-img' /> 
		          	</div>
		          </ModalHeader>
		          <ModalBody>
		          	<Typography use="display2" tag="h1">
		          		{this.state.item.headline}
		          		<Typography
					        use="headline"
					        theme="text-secondary-on-background"
					        component='span'
					        style={{marginLeft: '0.5rem'}}
					        >
					      	{String(this.state.item.year) + " | " + this.state.item.industry}
			      		</Typography>
		          	</Typography>
		          	<Typography use="body2" tag="div">{this.state.item.description}</Typography>
		          	<div className="relevant-links-container">
		          		<Typography use="title"> Relevant Links </Typography> 
		          		<ul> 
		          			<li> <a href={this.state.item.relLinks}> {this.state.item.relLinks} </a> </li>
		          		</ul>
		          	</div> 
		          </ModalBody>
	        	</Modal>
			</div>
		)
	}
}